# Generated by Django 3.2 on 2021-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0005_auto_20210417_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='labor_location',
        ),
        migrations.AddField(
            model_name='post',
            name='labor_CurrentAddress',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='labor_ResidentAddress',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
