# Generated by Django 3.2 on 2021-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0006_auto_20210418_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bank_cover',
            field=models.ImageField(default=0, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category_choice',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='labor_email',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='labor_signature',
            field=models.ImageField(default=0, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='member_choice',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
