# Generated by Django 3.2 on 2021-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0007_auto_20210421_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ID_back',
            field=models.ImageField(upload_to='image/', verbose_name='身份證正面'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ID_front',
            field=models.ImageField(upload_to='image/', verbose_name='身份證正面'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bank_cover',
            field=models.ImageField(upload_to='image/', verbose_name='銀行存摺封面'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_choice',
            field=models.CharField(choices=[('9A', '9A 執行業務所得'), ('9B', '9B 稿費')], max_length=3, verbose_name='申報類別'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_CurrentAddress',
            field=models.CharField(max_length=60, verbose_name='通訊地址'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_ID',
            field=models.CharField(max_length=20, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_Phone',
            field=models.CharField(max_length=20, verbose_name='連絡電話'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_ResidentAddress',
            field=models.CharField(max_length=60, verbose_name='戶籍地址'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_bank',
            field=models.CharField(max_length=20, verbose_name='銀行名(含分行)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_bankaccount',
            field=models.CharField(max_length=20, verbose_name='銀行帳號'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_bankname',
            field=models.CharField(max_length=20, verbose_name='銀行戶名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_email',
            field=models.CharField(max_length=20, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='post',
            name='labor_name',
            field=models.CharField(max_length=20, verbose_name='領款人姓名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='member_choice',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=3, verbose_name='職業工業會員'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(verbose_name='專案金額'),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_name',
            field=models.CharField(max_length=20, verbose_name='專案名稱'),
        ),
    ]
