# Generated by Django 3.2 on 2021-04-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0008_auto_20210423_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='labor_signature',
        ),
    ]
