# Generated by Django 3.2 on 2021-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0010_auto_20210423_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='labor_signature',
            field=models.FileField(upload_to='image/', verbose_name='簽名'),
        ),
    ]
