# Generated by Django 3.2 on 2021-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0002_auto_20210415_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labor_ID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='labor_Phone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
