# Generated by Django 3.2 on 2021-04-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0004_auto_20210417_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ID_back',
            field=models.ImageField(default=0, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ID_front',
            field=models.ImageField(default=0, upload_to='image/'),
            preserve_default=False,
        ),
    ]
