# Generated by Django 3.2 on 2021-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0011_alter_post_labor_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='labor_CurrentAddress',
        ),
        migrations.AddField(
            model_name='post',
            name='pay_complete',
            field=models.BooleanField(blank=True, default=False, verbose_name='付款完成'),
        ),
    ]
