# Generated by Django 3.2 on 2021-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetapp', '0014_alter_post_labor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='labor_signature',
            field=models.FileField(blank=True, upload_to='image/', verbose_name='簽名'),
        ),
    ]
